# Default server configuration.
db:
  migrate:
    database: angel
    username: root
    password: password
  web:
    database: angel
    username: username
    password: password
host: 127.0.0.1
mongo_db: mongodb://localhost:27017/dropbox
port: 3000
google:
  id: 879916772461-i7htk1jo48ubv18dbe9pvce4m6lbka9n.apps.googleusercontent.com
  secret: ZH3uaWy7Jtb7jtVRLcRRBdD0
  redirect_uri: http://localhost:3000/api/auth/google/callback
uploads:
  path: web/uploads
  public: uploads